config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :categories
  resources :wishlists do
    resources :purchases
  end

  resources :profiles
  # get '/users/:id/products', to: 'users#products', as: 'user_products'
  get '/users/:id/wishlists', to: 'users#wishlists', as: 'user_wishlists'

  get '/products', to: 'products#index', as: 'my_products'
  get '/wishlists', to: 'wishlists#index', as: 'my_wishlists'
  get '/profiles/', to: 'profiles#show', as: 'my_profile'
  get '/sold/', to: 'users#seller_history', as: 'my_sales'
  get '/ticked-off', to: 'users#wishlist_history', as: 'my_wishlist_history'
  get '/purchase-no-wishlist/:id', to: 'purchases#no_wishlist', as: 'purchase_no_wishlist'
  post '/purchase-no-wishlist/', to: 'purchases#no_wishlist_create', as: 'purchase_no_wishlist_create'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :user_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @profile = @user.profile
  end

  def create
    @user = current_user
    @profile = Profile.new(profile_params2)
    @profile.user_id = @user.id
    @profile.save
    # byebug
    redirect_to my_profile_path
  end

  def edit
    @profile = Profile.find(params[:id])
    @user = current_user
  end

  def show
    @profile = Profile.find(params[:id])
    @user = current_user
  end

  def update
    @profile = Profile.find(params[:id])
    @user = current_user

    if @profile.update(profile_params)
      flash[:success] = "Profile succesfully updated"
      redirect_to @user.profile
    else
      render 'edit'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:name, :phone_no, :street_number, :street_address, :suburb, :state, :postcode)
  end

  def profile_params2
    params.permit(:name, :phone_no, :street_number, :street_address, :suburb, :state, :postcode)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<p class="page-title">My Profile</p>
  <div class="new-profile-form">
    <div class="new-profile-form-container">
      <%= form_with model: @profile, local: true  do |form| %>
       <div class="form-group-new">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control", placeholder: "Name"%>
        </div>

        <div class="form-group form-group-new">
          <%= form.label :phone_no %>
          <%= form.telephone_field :phone_no, class: "form-control", placeholder: "Phone"%>
        </div>

        <div class="form-group form-group-new">
          <%= form.label :street_number %>
          <%= form.text_field :street_number, class: "form-control", placeholder: "Street number" %>
        </div>

        <div class="form-group form-group-new">
          <%= form.label :street_address %>
          <%= form.text_field :street_address, class: "form-control", placeholder: "Street address" %>
        </div>

      <div class="form-group form-group-new">
        <%= form.label :suburb %>
        <%= form.text_field :suburb, class: "form-control", placeholder: "Suburb" %>
      </div>

      <div class="form-group form-group-new form-group-state">
        <%= form.label :state %>
        <%= form.select :state, "<option>New South Wales</option><option>Victoria</option><option>Queensland</option><option>Western Australia</option><option>South Australia</option><option>Tasmania</option><option>Australian Capital Territory</option><option>Northern Territory</option>".html_safe  %>
      </div>

      <div class="form-group form-group-new">
        <%= form.label :postcode %>
        <%= form.text_field :postcode, class: "form-control", placeholder: "Postcode" %>
      </div>

        <%#= form.text_field :category_ids, multiple: true %>
        <%= form.submit "Save", class: "btn btn-yellow" %>
      <% end %>
    </div>
  </div>

app/views/profiles/index.html.erb
<p class="page-title">My Profile</p>

  <% if @user.profile == nil %>
  
    <div class="new-profile-form">
    
      <div class="new-profile-form-container">
        <p class="profile-subtitle">You don't have a profile - create one now!</p>
        <%= form_with model: @profile, local: true  do |form| %>
        
          <div class="form-group-new">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control", placeholder: "Name"%>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :phone_no %>
            <%= form.telephone_field :phone_no, class: "form-control", placeholder: "Phone"%>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :street_number %>
            <%= form.text_field :street_number, class: "form-control", placeholder: "Street number" %>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :street_address %>
            <%= form.text_field :street_address, class: "form-control", placeholder: "Street address" %>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :suburb %>
            <%= form.text_field :suburb, class: "form-control", placeholder: "Suburb" %>
          </div>

        <div class="form-group form-group-new form-group-state">
          <%= form.label :state %>
          <%= form.select :state, "<option>New South Wales</option><option>Victoria</option><option>Queensland</option><option>Western Australia</option><option>South Australia</option><option>Tasmania</option><option>Australian Capital Territory</option><option>Northern Territory</option>".html_safe  %>
        </div>

        <div class="form-group form-group-new">
          <%= form.label :postcode %>
          <%= form.text_field :postcode, class: "form-control", placeholder: "Postcode" %>
        </div>

        <%#= form.text_field :category_ids, multiple: true %>
        <%= form.submit "Save", class: "btn btn-yellow" %>
      </div>  
    </div>    
  <% end %>
  <% elsif %>
  
  <div class="new-profile-form">
    <div class="profile-container">
      <div class="profile-card">
        <h5 class="profile-card-header"><%= @user.profile.name %></h5>
        
        <div class="card-body profile-card-body">
            
            <h5 class="profile-card-text">Address</h5>
            <p class="card-text"><%= @user.profile.street_number %> <%= @user.profile.street_address %></p> 
            <p class="card-text"><%= @user.profile.suburb %> </p>
            <p class="card-text"><%= @user.profile.state %> </p>
            <p class="card-text"><%= @user.profile.postcode %></p>

            <h5 class="profile-card-text">Phone</h5>
            <p class="card-text"><%= @user.profile.phone_no %></p>

            <div class="profile-button">
            <%= link_to "Edit Profile", edit_profile_path(@profile), class: "btn btn-yellow" %>
            <% end %>
            </div>

        </div>
      </div>
    </div>
</div>

app/views/profiles/show.html.erb
<p class="page-title">My Profile</p>

<% if @user.profile == nil %>
  
    <div class="new-profile-form">
    
      <div class="new-profile-form-container">
        <p class="profile-subtitle">You don't have a profile - create one now!</p>
        <%= form_with model: @profile, local: true  do |form| %>
        
          <div class="form-group-new">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control", placeholder: "Name"%>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :phone_no %>
            <%= form.telephone_field :phone_no, class: "form-control", placeholder: "Phone"%>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :street_number %>
            <%= form.text_field :street_number, class: "form-control", placeholder: "Street number" %>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :street_address %>
            <%= form.text_field :street_address, class: "form-control", placeholder: "Street address" %>
          </div>

          <div class="form-group form-group-new">
            <%= form.label :suburb %>
            <%= form.text_field :suburb, class: "form-control", placeholder: "Suburb" %>
          </div>

        <div class="form-group form-group-new form-group-state">
          <%= form.label :state %>
          <%= form.select :state, "<option>New South Wales</option>Victoria<option>Queensland</option><option>Western Australia</option><option>South Australia</option><option>Tasmania</option><option>Australian Capital Territory</option><option>Northern Territory</option>".html_safe  %>
        </div>

        <div class="form-group form-group-new">
          <%= form.label :postcode %>
          <%= form.text_field :postcode, class: "form-control", placeholder: "Postcode" %>
        </div>

        <%#= form.text_field :category_ids, multiple: true %>
        <%= form.submit "Save", class: "btn btn-yellow" %>
      </div>  
    </div>    
  <% end %>
  <% elsif %>

  <div class="new-profile-form">
    <div class="profile-container">
      <div class="profile-card">
        <h5 class="profile-card-header"><%= @user.profile.name %></h5>
        
        <div class="card-body profile-card-body">
            
            <h5 class="profile-card-text">Address</h5>
            <p class="card-text"><%= @user.profile.street_number %> <%= @user.profile.street_address %></p> 
            <p class="card-text"><%= @user.profile.suburb %> </p>
            <p class="card-text"><%= @user.profile.state %> </p>
            <p class="card-text"><%= @user.profile.postcode %></p>

            <h5 class="profile-card-text">Phone</h5>
            <p class="card-text"><%= @user.profile.phone_no %></p>

            <div class="profile-button">
            <%= link_to "Edit Profile", edit_profile_path(@profile), class: "btn btn-yellow" %>
            <% end %>
            </div>
        </div>
      </div>
    </div>
</div>