config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :categories
  resources :wishlists do
    resources :purchases
  end

  resources :profiles
  # get '/users/:id/products', to: 'users#products', as: 'user_products'
  get '/users/:id/wishlists', to: 'users#wishlists', as: 'user_wishlists'

  get '/products', to: 'products#index', as: 'my_products'
  get '/wishlists', to: 'wishlists#index', as: 'my_wishlists'
  get '/profiles/', to: 'profiles#show', as: 'my_profile'
  get '/sold/', to: 'users#seller_history', as: 'my_sales'
  get '/ticked-off', to: 'users#wishlist_history', as: 'my_wishlist_history'
  get '/purchase-no-wishlist/:id', to: 'purchases#no_wishlist', as: 'purchase_no_wishlist'
  post '/purchase-no-wishlist/', to: 'purchases#no_wishlist_create', as: 'purchase_no_wishlist_create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :user_id, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :products
  has_many :wishlists
  has_one :profile
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :wishlist_categories
  has_many :categories, through: :wishlist_categories
  validates :user_id, presence: true
end

app/models/wishlist_category.rb
class WishlistCategory < ApplicationRecord
  belongs_to :wishlist
  belongs_to :category
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.order('created_at DESC')
    @categories = Category.all
    @user = current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.all.order('created_at DESC')
    @user = current_user
  end

  def new
    @product = Product.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.save
    flash[:success] = "Product successfully listed. Good luck!"

    redirect_to product_path(@product)
  end

  def show
    @product = Product.find(params[:id])
    check_user(@product)
  end

  def edit
    @product = Product.find(params[:id])
    check_user(@product)
  end

  def update
    @product = Product.find(params[:id])
   
    if @product.update(product_params)
      flash[:success] = "Product successfully updated"
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "Product was successfully deleted"
    
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, images: [], category_ids: [])
  end

  def check_user(product)
    if current_user.id != product.user_id
      flash[:notice] = "You are not authorized to view that content"
      redirect_to root_path
      return
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @profile = @user.profile
  end

  def create
    @user = current_user
    @profile = Profile.new(profile_params2)
    @profile.user_id = @user.id
    @profile.save
    # byebug
    redirect_to my_profile_path
  end

  def edit
    @profile = Profile.find(params[:id])
    @user = current_user
  end

  def show
    @profile = Profile.find(params[:id])
    @user = current_user
  end

  def update
    @profile = Profile.find(params[:id])
    @user = current_user

    if @profile.update(profile_params)
      flash[:success] = "Profile succesfully updated"
      redirect_to @user.profile
    else
      render 'edit'
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:name, :phone_no, :street_number, :street_address, :suburb, :state, :postcode)
  end

  def profile_params2
    params.permit(:name, :phone_no, :street_number, :street_address, :suburb, :state, :postcode)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    # @user_products = @user.products.all
  end

  def products
    @user_products = @user.products
  end

  def wishlists
    @user_wishlists = @user.wishlists
  end

  def profile
    @user_profile = @user.profile
  end

  def wishlist_history
    @user = current_user
    @purchases = Purchase.all.order('created_at DESC')
  end

  def seller_history
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert alert-success", error: "alert alert-danger", alert: "alert alert-warning", notice: "alert alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "#{bootstrap_class_for(msg_type)}", role: "alert") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('wishlist.ico'), :rel => 'icon', :type =>  'image/png' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.filestyle/1.1.0/js/bootstrap-filestyle.min.js"> </script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render '/layouts/shared/navigation.html.erb' %>
    <%= render '/layouts/shared/messages.html.erb' %>
    <%= render "/layouts/shared/homepage_slider.html.erb" if current_page?(root_path) %>
    <%= render "/layouts/shared/homepage_separator.html.erb" if current_page?(root_path) %>
    <%= yield %>
    <%= render '/layouts/shared/bottom_nav.html.erb' %>
  </body>
</html>

app/views/layouts/shared/_bottom_nav.html.erb
<div class="the-core-of-earth">
  <div class="divider">
    <div class="left">
      <%= link_to "Wishlist", root_path, class: "footer-wishlist" %><span class="copyright">&#169;</span>
    </div>
    <div class="middle">
      <i class="fab fa-twitter footer-icon fa-2x"></i>
      <i class="fab fa-instagram footer-icon fa-2x"></i>
      <i class="fab fa-facebook footer-icon fa-2x"></i>
    </div>
  </div>
</div>

app/views/layouts/shared/_homepage_separator.html.erb
<div class="site-section site-section-sm site-blocks-1">
  <%# <div class="container"> %>
    <div class="row separator">
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags" data-aos="fade-up" data-aos-delay="">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon"><i class="fa fa-shopping-bag"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">BUY</p>
        </div>
        <p class="separator-text">Select from a wide range of products and contact the seller directly.</p>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags" data-aos="fade-up" data-aos-delay="100">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon"><i class="fas fa-piggy-bank"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">SELL</p>
        </div>
        <p class="separator-text">Sell to hundreds of buyers <br> No bidding, no hassles</p>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags" data-aos="fade-up" data-aos-delay="200">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon heart"><i class="fa fa-heart"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">WISH</p>
        </div>
        <p class="separator-text">Can't see what you want? <br> Make a wishlist and we'll find a match!</p>
      </div>
    </div>
  <%# </div> %>
</div>

app/views/layouts/shared/_homepage_slider.html.erb
<div class="home-page-content">
  <div class="main-page-content">
  <h1><span class="header-font">Welcome to Wishlist</span></h1>
    <div>
      <h4>Where your wishes come true</h4>
    </div>
    <% if user_signed_in? == false %>
      <div>
        <%= link_to "Make a wishlist", new_user_registration_path, class: "btn btn-succes btn-yellow button" %>
      </div>
    <% elsif user_signed_in? == true %>
      <div>
        <%= link_to "Make a wishlist", new_wishlist_path, class: "btn btn-succes btn-yellow button" %>
      </div>
    <% end %>
  </div>
  <%= image_tag("slide_1.jpg", class:"banner-image") %>
</div>

app/views/layouts/shared/_messages.html.erb
<%= flash_messages %>

app/views/layouts/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Wishlist", root_path,  class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? == false %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'My Products', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'My Wishlists', new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to 'LOG IN', new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0 skinny-button btn-sm" %>
        <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0 skinny-button btn-sm" %>
      </form>
    </div>
  <% else %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Products
            <i class="fa fa-angle-down"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'My Products', my_products_path, class: "dropdown-item" %>
            <%= link_to 'New Product', new_product_path, class: "dropdown-item" %>
            <%= link_to 'My Sales', my_sales_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Wishlists
            <i class="fa fa-angle-down"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'My Wishlists', my_wishlists_path, class: "dropdown-item" %>
            <%= link_to 'New Wishlist', new_wishlist_path, class: "dropdown-item" %>
            <%= link_to 'Wishlist History', my_wishlist_history_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Profile 
            <i class="fa fa-user"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'My Profile', my_profile_path, class: "dropdown-item" %>
            <%= link_to 'Account Settings', edit_user_registration_path, class: "dropdown-item"  %>
            <%#= link_to 'My Products', my_products_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0 skinny-button btn-sm" %>
      </form>
    </div>
  <% end %>
</nav>

app/views/layouts/shared/_stripe.html.erb
<%= form_tag wishlist_purchases_path(@wishlist, @product) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Purchase <%= @product.name %>"
          data-amount="<%= @product.price * 100 %>"
          data-locale="auto"
          data-currency=aud
          data-label="Buy Now"></script> 
<% end %>

app/views/layouts/shared/_stripe_no_wishlist.html.erb
<%= form_tag purchase_no_wishlist_create_path(@product) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>$<%= '%.2f' % @product.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Purchase <%= @product.name %>"
          data-amount="<%= @product.price * 100 %>"
          data-locale="auto"
          data-currency=aud
          data-label="Buy Now"></script> 
<% end %>