config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :categories
  resources :wishlists do
    resources :purchases
  end

  resources :profiles
  # get '/users/:id/products', to: 'users#products', as: 'user_products'
  get '/users/:id/wishlists', to: 'users#wishlists', as: 'user_wishlists'

  get '/products', to: 'products#index', as: 'my_products'
  get '/wishlists', to: 'wishlists#index', as: 'my_wishlists'
  get '/profiles/', to: 'profiles#show', as: 'my_profile'
  get '/sold/', to: 'users#seller_history', as: 'my_sales'
  get '/ticked-off', to: 'users#wishlist_history', as: 'my_wishlist_history'
  get '/purchase-no-wishlist/:id', to: 'purchases#no_wishlist', as: 'purchase_no_wishlist'
  post '/purchase-no-wishlist/', to: 'purchases#no_wishlist_create', as: 'purchase_no_wishlist_create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all.order('created_at DESC')
    @categories = Category.all
    @user = current_user
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="banner">
  <div class="banner-ad">
  </div>
</div>
<%# <p class="home">All Products</p> %>
<% if user_signed_in? == false %>
  <div class="row cards index-products">
    <% @products.each do |product| %>
      <% if product.sold == false %>    
        <div class="col-sm-3">
          <div class="card card2">
            <% if product.images.any? %>
              <%= image_tag product.images.first, class: "card-img-top thumbnail" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text">$<%= '%.2f' % product.price %></p>
              <%= link_to "Checkout Now", new_user_registration_path, class: "btn btn-succes btn-yellow" %>
            </div>
          </div>
        </div>
      <% end %>
    <%end %>
    <div class="banner-ad2">
    </div>
  </div>
  <div class="product-not-found">
    <div class="left">
      <p class="product-not-found-title">Don't see what you need?</p>
      <p class="product-not-found-text">Sometimes we can't find what we're looking for. That's OK!</p>
      <p class="product-not-found-text">With <span class="mini-wishlist">Wishlist</span> we match you with products that fit your search.</p>
      <p class="product-not-found-text">It's really easy. Make a Wishlist now!</p>
    </div>
    <div class="right">
      <%= link_to "Make a wishlist", new_user_registration_path, class: "btn btn-succes btn-yellow" %>
    </div>
  </div>
<% elsif user_signed_in? == true %>
  <div class="row cards index-products">
    <% @products.each do |product| %>
      <% if product.sold == false && product.user_id != current_user.id%>
        <div class="col-sm-3">
          <div class="card card2">
            <% if product.images.any? %>
              <%= image_tag product.images.first, class: "card-img-top thumbnail" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text">$<%= '%.2f' % product.price %></p>
              <%= link_to "Checkout Now", purchase_no_wishlist_path(product), class: "btn btn-succes btn-yellow" %>
            </div>
          </div>
        </div>
      <% end %>
    <%end %>
    <div class="banner-ad2">
    </div>
  </div>
  <div class="product-not-found">
    <div class="left">
      <p class="product-not-found-title">Don't see what you need?</p>
      <p class="product-not-found-text">Sometimes we can't find what we're looking for. That's OK!</p>
      <p class="product-not-found-text">With <span class="mini-wishlist">Wishlist</span> we match you with products that fit your search.</p>
      <p class="product-not-found-text">It's really easy</p>
    </div>
    <div class="right">
      <%= link_to "Make a wishlist", new_wishlist_path, class: "btn btn-succes btn-yellow" %>
    </div>
  </div>
<% end %>