config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :categories
  resources :wishlists do
    resources :purchases
  end

  resources :profiles
  # get '/users/:id/products', to: 'users#products', as: 'user_products'
  get '/users/:id/wishlists', to: 'users#wishlists', as: 'user_wishlists'

  get '/products', to: 'products#index', as: 'my_products'
  get '/wishlists', to: 'wishlists#index', as: 'my_wishlists'
  get '/profiles/', to: 'profiles#show', as: 'my_profile'
  get '/sold/', to: 'users#seller_history', as: 'my_sales'
  get '/ticked-off', to: 'users#wishlist_history', as: 'my_wishlist_history'
  get '/purchase-no-wishlist/:id', to: 'purchases#no_wishlist', as: 'purchase_no_wishlist'
  post '/purchase-no-wishlist/', to: 'purchases#no_wishlist_create', as: 'purchase_no_wishlist_create'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :wishlist_categories
  has_many :categories, through: :wishlist_categories
  validates :user_id, presence: true
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!
  def index
    @wishlists = Wishlist.all
    @user = current_user
    @products_without_wishlists = Purchase.all.find_by(buyer_id: @user.id)
  end

  def new
    @wishlist = Wishlist.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @wishlist = Wishlist.new(wishlist_params)
    @wishlist.user = current_user

    @wishlist.save
    flash[:success] = "Wishlist successfully created"

    # redirect_to wishlist_path(@wishlist)
    redirect_to my_wishlists_path
  end

  def show
    @wishlist = Wishlist.find(params[:id])
    check_user(@wishlist)
    @matches = []
    @wishlist_categories = @wishlist.categories
    @w_cat_ids = @wishlist_categories.ids
    @products = Product.all.order('created_at DESC')
    @products.each do |product|
      if (product.categories.ids & @w_cat_ids).any? && product.user_id != @wishlist.user.id
        @matches << product
      end
    end
  end

  def edit
    @wishlist = Wishlist.find(params[:id])
    check_user(@wishlist)
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def update
    @wishlist = Wishlist.find(params[:id])
   
    if @wishlist.update(wishlist_params)
      flash[:success] = "Wishlist successfully updated"
      redirect_to @wishlist
    else
      render 'edit'
    end
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy
    flash[:success] = "Wishlist was successfully deleted"
    
    redirect_to wishlists_path
  end


  private
  def wishlist_params
    params.require(:wishlist).permit(:name, :description, :price, images: [], category_ids: [])
  end

  def check_user(wishlist)
    if current_user.id != wishlist.user_id
      flash[:notice] = "You are not authorized to view that content"
      redirect_to root_path
      return
    end
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/edit.html.erb
<p class="page-title">Edit Wishlist</p>
<div class="new-product-form">
  <div class="new-product-form-container">
    <%= form_with model: @wishlist, local: true  do |form| %>
      <div class="form-group-new">
        <%= form.label :name, "Product Name" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Product Name" %>
      </div>
      <div class="form-group-categories">
        <%= form.label :category_ids, "Categories" %>
        <%= form.select :category_ids,
          Category.all.order('name ASC').map { |k| [k.name, k.id] },
                          { include_blank: true },
                          { :multiple => true, class: 'chosen-select' }
        %>
      </div>
      <div class="form-group-new new-description">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: "6", placeholder: "Product Description" %>
      </div>
      <div class="form-group-new new-price">
        <%= form.label :price, "Asking Price" %>
        <div class="input-group-prepend">
          <div class="input-group-text">$</div>
          <%= form.number_field(:price, min: 1.00, step: 0.01, class: "form-control", placeholder: "Price in $AUD")%>
        </div>
      </div>
      <%= form.submit  "Edit Wishlist", class: "btn btn-yellow btn-new-product" %>
    <% end %>
  </div>
</div>

app/views/wishlists/index.html.erb
<p class="page-title">My Wishlists</p>
<div class="myproducts">
  <ul class="myproducts-list">
    <% @user.wishlists.order('created_at DESC').each do |wishlist| %>
      <% if wishlist.completed == false %>
        <li class="list-group-item product-listed">
          <div class="product-duo">
            <h3 class="product-list-item-icon"><i class="fas fa-heart pink-pig"></i></h3>
            <div class="separator">
              <h5 class="product-list-item"><%= wishlist.created_at.strftime("%d-%m-%Y") %></h5>
              <h5 class="product-list-item">Wishlist Name:</h5>
              <h5 class="product-list-item"><%= wishlist.name %></h5>
            </div>
          </div>
          <%= link_to "Show Matches", wishlist_path(wishlist), class: "btn btn-succes btn-yellow button products-button" %>
        </li>      
      <% end %>
    <% end %>
  </ul>
</div>

app/views/wishlists/new.html.erb
<p class="page-title">New Wishlist</p>
<div class="new-product-form">
  <div class="new-product-form-container">
    <%= form_with model: @wishlist, local: true  do |form| %>
      <div class="form-group-new">
        <%= form.label :name, "Wishlist Name" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Wishlist Name" %>
      </div>
      <div class="form-group-categories">
        <%= form.label :category_ids, "Categories" %>
        <%= form.select :category_ids,
          Category.all.order('name ASC').map { |k| [k.name, k.id] },
                          { include_blank: true },
                          { :multiple => true, class: 'chosen-select' }
        %>
      </div>
      <div class="form-group-new new-description">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: "6", placeholder: "Wishlist Description" %>
      </div>
      <div class="form-group-new new-price">
        <%= form.label :price, "Asking Price" %>
        <div class="input-group-prepend">
          <div class="input-group-text">$</div>
          <%= form.number_field(:price, min: 1.00, step: 0.01, class: "form-control", placeholder: "Price in $AUD")%>
        </div>
      </div>
      <%= form.submit  "Create Wishlist", class: "btn btn-yellow btn-new-product" %>
    <% end %>
  </div>
</div>

app/views/wishlists/show.html.erb
<p class="page-title">Wishlist</p>
<div class="wishlist-container">
 
  <div class="wishlist-show">
    <div class="product-show-details">
      <% if @wishlist.completed == false %>
        <h3><%= @wishlist.name %></h3>
        <div class="description-box">
          <% description_array = @wishlist.description.split(".") %>
          <% description_array.each do |string| %>
            <p><%= string %></p>
          <% end %>
        </div>
        <h5 class="product-price">Price $<%= '%.2f' % @wishlist.price %></h5>
        <p class="product-update-button-top"><%= link_to edit_wishlist_path(@wishlist), class:'btn btn-yellow product-button' do %>
              <span class="far fa-edit"></span>
              Edit wishlist
            <% end %>
        </p>
        <p><%= link_to wishlist_path(@wishlist),
            method: :delete,
            data: { confirm: '  Are you sure?' }, class: 'btn btn-danger product-button' do %>
              <span class="fa fa-trash-alt"></span>
                Delete wishlist
              <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<div class="site-section site-section-sm site-blocks-1 wishlist-separator">
  <%# <div class="container"> %>
    <div class="row separator">
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags wishlist-inner" data-aos="fade-up" data-aos-delay="">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon"><i class="fa fa-heart"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">Match</p>
        </div>
        <p class="separator-text">Submit your Wishlist and we match you instantly.</p>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags wishlist-inner" data-aos="fade-up" data-aos-delay="100">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon"><i class="fas fa-glasses"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">VIEW</p>
        </div>
        <p class="separator-text">Like what you see? <br> Go ahead and view it!</p>
      </div>
      <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4 aos-init aos-animate tags wishlist-inner" data-aos="fade-up" data-aos-delay="200">
        <div class="duo">
          <div class="icon align-self-center">
            <h2 class="font-awesome-icon heart"><i class="fas fa-shopping-cart"></i><h2>
          </div>
        </div>
        <div class="text">
          <p class="text-uppercase">BUY</p>
        </div>
        <p class="separator-text">Your purchase is one step away! <br> Buy it now!</p>
      </div>
    </div>
  <%# </div> %>
</div>
<div class="banner3-container">
  <div class="banner-ad3">
  </div>
</div>
<p class="match-title text-center"></i><span class="matches-wishlist-title"> Matches </span></p>
<div class="match-container">
  <div class="row cards">                
    <% @matches.each do |match| %>
      <% if match.sold == false %>
        <div class="col-sm-3 wishlist-show-card">
          <div class="card" style="width: 18rem;">
            <% if match.images.any? %>
              <%= image_tag match.images.first, class: "card-img-top thumbnail" %>
            <% end %>
            <%# <div class="description-box"> %>
            <div class="card-body">
              <h5 class="card-title"><%= match.name %></h5>
              <%# description_array2 = match.description.split(".") %>
              <%# description_array2 do |string| %>
              <%# end %>
              <h5 class="product-price">Price $<%= '%.2f' % match.price %></h5>
              <%= link_to "View", wishlist_purchase_path(@wishlist, match), class: "btn btn-yellow" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div> 